### ISSUE TITLE
CHANGE the database used in geolocation_service

### ISSUE THREAD

**Issue by brunolcarli** [sosbrumadinho/brumadinho_location#46]
The service is using sqlite3 as database, this is not a good database for production.

Must change to another database such as MySQL.

**Comment by andersonmalheiro** [comment]
This is simple, as the project is being build with Django it's only necessary to change some configs on the **"settings.py"** to use a Postgres or MySQL database.

**Comment by brunolcarli** [comment]
Yes, i only opened the issue cuz yesterday i was going to sleep and now im at work. This is for remembering so i can do after work or if anyone could do this in the meantime that i cannot.

**Comment by andersonmalheiro** [comment]
I'm also at work now, so when I get home at night I'll see what I can do to help. I have a little experience with Django, so I'll try to help you with the project too man.

**Comment by brunolcarli** [comment]
Thanks @andersonmalheiro I appreciate your help :D

**Comment by isouzasoares** [comment]
@brunocroh maybe using geodjango with postgis is a good idea, if you want I can help.

**Comment by cacarrara** [comment]
Probably the production database is going to be Postgres. As this is not something we can address immediately (there's still some issues to be solved before) I'm closing this issue only trying to organize the work and not scatter the efforts that is coming.
