### ISSUE TITLE
Arquivo de listagem de pessoas com comparação local com online

### ISSUE THREAD

**Issue by JeanGoncalves** [sosbrumadinho/brumadinho_location#52]
Criar arquivo de comparação do **data.csv** com o **online** para classificar as pessoas que já foram encontradas

**Comment by brunolcarli** [comment]
As suggested in #13:

### English:

Create comparison files from **data.csv** with the **online data** for classifying the already found people.

**Comment by vaniaon** [comment]
@JeanGoncalves nice suggestion. Are you woking on it?
