### ISSUE TITLE
Changing backend to Flask application API

### ISSUE THREAD

**Issue by felipebastosweb** [sosbrumadinho/brumadinho_location#56]
Creating a branch release/flask_api for backend

**Comment by cacarrara** [comment]
I'm not completely sure about that. We're going to be (at least initially) heavily based on relational databases (Django ORM can be an advantage for that) and also we'll have to store geolocation data and Django Postgis integration can also be better than having Flask.

What am I missing here? What are the benefits adopting Flask?

**Comment by brunolcarli** [comment]
To change whats already created i think is just rework. Create new API for new services that was not already implemented is acceptable, if it play along the requirements mentioned by @cacarrara here in the above reply.

We dont have too much time for reworking or loosing time discussing and choosing the most confortable or best framework. There are people out there praying to be found by rescue teams before giving a last last breath.

So thats what i think, sorry about the honesty.
