### ISSUE TITLE
Looking for mechanical engineer. Who is the point of contact?

### ISSUE THREAD

**Issue by ronflima** [sosbrumadinho/brumadinho_location#79]
I have asked a friend to search for a specialist in fluid mechanics at USP, Ribeirão Preto. However, if she find someone to help, who is the point of contact in order to brief this professional about the situation? 

Please, advise who's to contact so I can provide the point-of-contact to my friend, so she can put the fluid mechanics specialist in contact with the project leader.

**Comment by cacarrara** [comment]
I'm helping with the project organization together with others who starter it. My contacts can be found here: https://caiocarrara.com.br/contato.html
