### ISSUE TITLE
[Pergunta] Develop branch?

### ISSUE THREAD

**Issue by cacarrara** [sosbrumadinho/brumadinho_location#91]
Olá pessoas.

Acabei chegando um pouco tarde no projeto, mas quero muito ajudar. Para tornar as coisas mais simples, eu gostaria de manter somente a branch `master` como ponto de merge de Pull Requests e deletar a branch `develop` do repositório. Alguém de algo contra?

O fluxo para colaboração continua o mesmo e cada um pode abrir suas feature branches a vontade. Porém os merges deverão ser abertos e integrados somente na master.

Vou manter essa pergunta aberta por um tempo e se não houver nenhum ponto muito crítico contrário, irei deletar a develop.

Valeu!

**Comment by vaniaon** [comment]
Acho que funciona se tivermos o CI com os testes automatizados implementados. 
Senão, é melhor manter a develop

**Comment by vaniaon** [comment]
@cacarrara isso! pode apagar a develop
